### ISSUE TITLE
IndexError when run train_gcn.py

### ISSUE THREAD

**Issue by robotzheng** [Nik-V9/AirObject#1]
(airobj) oppoer@falcon:AirObject$ python './train/train_gcn.py' -c './config/train_gcn.yaml' -g 1
loading annotations into memory...
Done (t=25.07s)
creating index...
index created!
Finish cuda loading
load model from ./models/gcn_model_coco.pth
===> Saving state to: ./experiments/train_gcn/Mar29_03-52-26_gcn
  0%|▎                                                                                                                 | 3/1133 [00:09<1:00:20,  3.20s/it]
train:   0%|                                                                                                                       | 0/15 [00:09<?, ?it/s]
Traceback (most recent call last):
  File "./train/train_gcn.py", line 221, in <module>
    main()
  File "./train/train_gcn.py", line 218, in main
    train(configs)
  File "./train/train_gcn.py", line 108, in train
    object_filter = ann_mask[keypoints[:,0].T,keypoints[:,1].T]
IndexError: index 1029 is out of bounds for axis 0 with size 720

**Comment by Nik-V9** [comment]
Thank you for reaching out with your query.

I believe the problem is being caused due to the size differences between the annotation mask and extracted superpoint features.

The YT-VIS dataloader resizes the images and annotation masks to 720*1280. However, the Superpoint Inference script shared in the repo doesn't resize the images. A few videos in YT-VIS have a different resolution and would need to be resized during SuperPoint Inference. Please add the following lines to your superpoint inference script ([after line 59](https://github.com/Nik-V9/AirObject/blob/5937e64531f08449e81d2c90e3c6643727efbaf0/superpoint_extraction.py#L59)):
```
if (image.shape[0] != 720) or (image.shape[1] != 1280):
    image = cv2.resize(image, (1280, 720), interpolation=cv2.INTER_LINEAR)
```

Re-extracting SuperPoint Features with this fix should resolve the issue.
